DroidKaigi/conference-app-2019

data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/ApiModule.kt
data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/UserAgentInterceptor.kt

- None
- Just for a purpose to collect stats later on API side :)
- None

Configured HttpClient to send User-Agent etc.

---

.circleci/scripts/download_latest_apk

- None
- This repo is now public so circleci token is not required
- `master` branch should be compared with feature branches
- None

[wip] Changed the compared branch and remove the circleci token

---

.circleci/scripts/download_latest_apk

- None
- The title says everything
- NOne

Fixed a wrong syntax of curl command when downloading the apk built on master

---

.circleci/config.yml
scripts/parse_dg_response

- None
- This change is for us, reviewers.  We can try the changed app from the distribution from now :)
- None

To review easily, post the distribution link to GitHub comment

---

README.md

- Changed `AssistedInejct` to `AssistedInject`

fix_spelling_mistake

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- This is a retry for  #221 (CI fail)
-  #221

Fixed the backgroundTint of FloatingActionButton on Android 5.0

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ViewBinding.kt
feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
feature/session/src/main/res/layout/fragment_session_detail.xml
feature/session/src/main/res/layout/item_session.xml

- close #131 
- Add binding adapter for visibility
- Using binding adapter in layout
-
Before | After
:--: | :--:

Add binding adapter of visibility

---

frontend/android/src/main/res/menu/menu_toolbar.xml

- none
-Timeline will be displayed when the search icon's long tap
-
Before | After
:--: | :--:

replace session_label with search_label

---

.circleci/config.yml
scripts/.envrc
scripts/.gitignore
scripts/destroy_distribution
scripts/parse_dg_response

- None
- master's job to destroy distributions always fail now 😇 
- I've fixed it by introducing new bash script
-

Fixed destroying distributions on master branch

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
frontend/android/src/main/res/layout/activity_main.xml
frontendcomponent/androidcomponent/src/main/res/values/themes.xml

- close #178
- 
-
Before | After
:--: | :--:

Remove searchHintIcon

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt

- Some time filter is not applied 😭 
Before | After
:--: | :--:

Fix bug of using different store

---

build.gradle
buildSrc/src/main/java/dependencies/Dep.kt
feature/about/build.gradle
feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/AboutFragment.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt
frontend/android/build.gradle
frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml

- close #146
- Implements license screen.
- https://developers.google.com/android/guides/opensource
Before | After
:--: | :--:

Add license feature

---

model/src/commonMain/kotlin/SessionType.kt

- close #249 
- Fixed session type id
- None
Before | After
:--: | :--:

Fixed session type id

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt

- close #266
- remove unnecessary null-check

remove unnecessary null-check

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- close #280
- Add `app:chipMinTouchTargetSize` to `fragment_session_detail.xml` \`s `simultaneous_interpretation_chip`
-
Before | After
:--: | :--:

add chipMinTouchTargetSize

---

feature/about/src/main/res/layout/header_about.xml

- Added ripple effect to ImageButton of about screen.  
Before | After
:--: | :--:

Added ripple effect to ImageButton of about screen

---

frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt

- none
- According to title.
Before | After
:--: | :--:

Close drawer when pressed back key while drawer opened.

---

feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/actioncreator/AnnouncementActionCreatorTest.kt

- Fix firestore conflict.
- `Rename FireStore -> Firestore` and `add unit test PRs` are confict

Fix firestore conflict

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt

- close #33 
- Suppress BottomSheetFragment replacement.
Before | After
:--: | :--:

 Suppress Fragment replacement

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/layout/fragment_session_detail.xml

- close #166
- add ProgressBar to fragment_session_detail
- add logic to SessionDetailFragment
-
Before | After
:--: | :--:

Add loading ProgressBar in session detail when you favorite

---

feature/session/src/main/res/layout/fragment_session_page.xml

Reverts DroidKaigi/conference-app-2019#323

Revert "Add space on both sides of the session tab."

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/layout/fragment_session_detail.xml

- close #292
- Added session message in session detail screen.
Before | After
:--: | :--:

Added session message in session detail screen

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
feature/session/src/main/res/values-ja/strings.xml
feature/session/src/main/res/values/strings.xml
model/src/commonMain/kotlin/Filters.kt

- close #318 
- Implemented the title when filtered.
Before | After
:--: | :--:

Show Filtered to sessions title

---

buildSrc/src/main/java/dependencies/Dep.kt
data/repository-impl/build.gradle
ext/log/build.gradle
ext/log/src/commonMain/kotlin/Logger.kt
ext/log/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/timber/Timber.kt
feature/session/build.gradle
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreator.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
feature/sponsor/build.gradle
feature/system/build.gradle
feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ErrorHandler.kt
frontend/android/build.gradle
frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt
frontend/android/src/main/java/io/github/droidkaigi/confsched2019/DebugApp.kt

- close #274 
- Timber support MPP from 5.0.0 snapshot, i try it!
- https://github.com/JakeWharton/timber
Before | After
:--: | :--:

Use Timber mpp

---

README.md

- None
- tsurai
- If anyone has screenshots, please let us know. Such materials would be helpful to explain this matter.
-

Added a note for PlayProtect dialogs

---

frontend/android/src/main/res/drawable/bg_navigation_footer.xml
frontend/android/src/main/res/layout/activity_main.xml
frontend/android/src/main/res/layout/layout_navigation_footer.xml
frontend/android/src/main/res/menu/menu_nav_drawer.xml
frontend/android/src/main/res/values-ja/strings.xml
frontend/android/src/main/res/values/strings.xml

- close #93
- Add the footer for navigation drawer
- Some design spec is unclear, so I implemented by my thought.
Feel free to tell me to change it!
Before | After
:--: | :--:

Add navigation drawer footer

---

.idea/dictionaries/dic.xml

- NONE
- SSIA
Before | After
:--: | :--:

Added coroutine to .idea/dictionaries/dic.xml

---

feature/session/src/main/res/layout/fragment_session_pages.xml

- NONE
- Fix Tab size when Landscape.
I do not know the design of Landscape, is it too big? 🤔 
- #342 
Before | After
:--: | :--:

Fix Tab size when Landscape

---

README.md

- None
- `Google Play Protect will show a warning` -> `Google Play Protect will show a warning dialog`
- Added a line return
-

Applied a bit of modification to README

---

data/firestore-impl/src/main/java/io/github/droidkaigi/confsched2019/data/firestore/FirestoreImpl.kt
data/firestore/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/firestore/FireStore.kt
data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/DataSessionRepository.kt
data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/mapper/SessionMappers.kt
data/repository/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/repository/SessionRepository.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreator.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
feature/session/src/main/res/layout/item_service_session.xml
feature/session/src/test/java/io/github/droidkaigi/confsched2019/SessionDummyDatas.kt
feature/session/src/test/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStoreTest.kt
model/src/commonMain/kotlin/Session.kt
model/src/commonMain/kotlin/SessionType.kt

- close #164
- Display favorite buttons with codelabs and change so that they can be favorite.
-
Before | After
:--: | :--:

Display favorite buttons with codelabs

---

scripts/checkout_pr_branch
scripts/fetch_droidkaigi_master

- None
- This script allows you to checkout the branch of the PR by its number
-

Added scripts to fetch repos for reviewers

---

feature/session/src/test/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStoreTest.kt

- None
- Not sure the exact reason but the cause is a needless statement. So let me remove it.
-

Removed a redandunt statement

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt

- close #151 
- Add animation to favorite button

Add animation to favorite button

---

frontend/android/src/main/res/layout/layout_navigation_footer.xml

- close None
- Fixed field deprecated in ConstraintLayout.
- https://androidstudio.googleblog.com/2017/10/constraintlayout-110-beta-2.html

Fixed, deprecated field in ConstraintLayout

---

data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/DataSessionRepository.kt

- close #409
- Fixed the filter to display correctly
- Changed the order of filters by name
Before | After
:--: | :--:

Fixed the filter to display correctly.

---

feature/announcement/src/main/res/layout/item_announcement.xml
frontendcomponent/androidcomponent/src/main/res/values/text_apperance.xml

- None
- Implemented font on info screen.
- ~~EmojiTextView -> EmojiAppCompatTextView~~
~~Because fontFamily is not applied in EmojiTextView.~~
Before | After
:--: | :--:

Implemented font on info screen

---

feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt

- close [#418](https://github.com/DroidKaigi/conference-app-2019/issues/418)
- Use named parameters

Use named parameters for creating AboutItem

---

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml

- None
- Fix warning `This may cause NPE so Data Binding will safely unbox it.`
-
Before | After
:--: | :--:

Fix databinding warning

---

feature/session/src/main/res/drawable/shape_dashed_line.xml
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/SponsorFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/item/DividerItem.kt
feature/sponsor/src/main/res/layout/item_divider.xml
feature/sponsor/src/main/res/layout/item_header.xml
feature/sponsor/src/main/res/layout/item_sponsor.xml
feature/sponsor/src/main/res/layout/item_sponsor_tall.xml

- close #420 
- Fixed of sponsor screen design.
- Card corner changed to 16dp.
- Added divider.
- Fixed title text style.
- Did code formatter.
Before | After
:--: | :--:

Fixed of design sponsor screen

---

frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt
frontend/android/src/main/res/layout/activity_main.xml

- close #413
- Show "not url decided" toast
Before | After
:--: | :--:

Show toast when click entire survey

---

data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/DataSessionRepository.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionPagesActionCreator.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStore.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
feature/session/src/main/res/layout/fragment_session_page.xml
feature/session/src/main/res/values/strings.xml
frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/action/Action.kt
model/src/commonMain/kotlin/Filters.kt
model/src/commonMain/kotlin/LangSupport.kt
model/src/commonMain/kotlin/SessionContents.kt
model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt

- close #316 
- Add simultaneous interpretation filter
- Add tests
Before | After(Japanese) | After(English)
:--: | :--: | :--:

Add simultaneous interpretation filter

---

feature/session/sampledata/service_session.json
feature/session/src/main/res/layout/fragment_session_detail.xml
feature/session/src/main/res/layout/item_session.xml
feature/session/src/main/res/values-ja/strings.xml
feature/session/src/main/res/values/strings.xml

- close #431 
- Add "for beginners" tag on item_session and fragment_session_detail
- None
name | Before | After
:--: | :--: | :--:
item_session | <img src="https://user-images.githubusercontent.com/18282993/51084811-874a9280-1773-11e9-99e9-35089b949f77.png" width="300" /> | <img src="https://user-images.githubusercontent.com/18282993/51084825-b5c86d80-1773-11e9-9d47-9379014a8167.png" width="300" />
fragment_session_detail | <img src="https://user-images.githubusercontent.com/18282993/51084819-a34e3400-1773-11e9-94a5-a884df5d35f2.png" width="300" /> | <img src="https://user-images.githubusercontent.com/18282993/51084828-bc56e500-1773-11e9-8edc-eec59283151d.png" width="300" />

Add "for beginners" tag

---

feature/announcement/src/main/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStore.kt
feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt
feature/session/src/test/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStoreTest.kt
frontendcomponent/androidtestcomponent/src/main/java/io/github/droidkaigi/confsched2019/widget/component/DirectDispatcher.kt

- The store's test is not in order, just checking if you can take the value and get it.
- This issue is needed for creating test issues

Refactor Store tests

---

data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/mapper/SessionMappers.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt
feature/session/src/main/res/layout/item_service_session.xml
feature/session/src/test/java/io/github/droidkaigi/confsched2019/SessionDummyDatas.kt
model/src/commonMain/kotlin/Session.kt
model/src/commonMain/kotlin/SessionContents.kt

- close #445
- Fix service session's title on English environments
-
Before | After
:--: | :--:

Fix service session's title on English environments

---

buildSrc/src/main/java/dependencies/Dep.kt
data/api-impl/build.gradle
data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiComponent.kt
data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/MainLoopDispatcher.kt
data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/InjectableKtorDroidKaigiApi.kt
data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/DroidKaigiApi.kt
data/repository/build.gradle
data/repository/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/repository/ResponseToModelMapper.kt
frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
frontend/ios/DroidKaigi 2019/SessionRepository.swift
frontend/ios/DroidKaigi 2019/ViewController.swift

- Now, we can use session data.
- We can open and confirm it by opening frontend/ios with Xcode.

iOS: Fetch sessions as model

---

buildSrc/src/main/java/dependencies/Dep.kt

- close #455 
- for fixing crash

Downgrade ktor

---

buildSrc/src/main/java/dependencies/Dep.kt
data/api-impl/build.gradle

- Down grade all of ktor versions for fixing build

Down grade all of ktor versions

---

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml

- close #467
- Change view id to snake case
-
Before | After
:--: | :--:

Change view id to snake case

---

feature/session/src/main/res/layout/item_session.xml

- close #477 
-Session listのfavoriteボタンにRippleを追加
-

Session listのfavoriteボタンにRipple追加

---

buildSrc/src/main/java/dependencies/Versions.kt
feature/about/build.gradle
feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutItem.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt
feature/about/src/main/res/layout/item_about.xml
feature/about/src/main/res/values/strings.xml
frontend/android/build.gradle

- close #476
- define versionName and versionCode to Versions.kts
- use it to build.gradle and about screen
-
Before | After
:--: | :--:

Fixed that about screen app version is not correct app version

---

feature/floormap/src/main/java/io/github/droidkaigi/confsched2019/floormap/ui/FloorMapFragment.kt
feature/floormap/src/main/res/layout/item_floor_map.xml
feature/floormap/src/main/res/values/strings.xml

- close #480 
- Add content description to floor map image
There is no difference which you can see by eye on the screen.

Add content description to floor map image

---

feature/announcement/sampledata/announcement.json

- close #482 
- Add comma to end of line
Before | After
:--: | :--:

Fix sample data of announcement #482

---

frontend/ios/README.md

- This is Android Repository, So I added How to build.

Create README for iOS

---

frontend/ios/README.md

Use carthage bootstrap instead of carthage update

---

feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutHeaderItem.kt

- None
- Fix repository link in AboutFragment: 2018 -> 2019

Fix repository link in AboutFragment

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SearchStore.kt

- None
Somehow SearchStore is in the actioncreator package.
Perhaps, it seems appropriate that SearchStore is in the store package.
None

Move SearchStore to store package from actioncreator package

---

frontend/ios/README.md

Hi I'm @ikesyo, a maintainer of Carthage 😄 Thanks for using it!
There should be no need to let Carthage build macOS variant and so on.

Update iOS README

---

build.gradle
buildSrc/src/main/java/dependencies/Dep.kt
feature/floormap/build.gradle
feature/floormap/src/main/java/io/github/droidkaigi/confsched2019/floormap/ui/widget/DisablePinchNestedScrollView.kt
feature/floormap/src/main/res/layout/item_floor_map.xml

- close #472
-  make pinching zoom possible
-
Before | After
:--: | :--:

Pinch zoom floor map

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt

- close #357 
- Add search session index(both of SpeechSessionItem and ServiceSessionItem)
- Fix the place of index from bottom to top
-
Before | After
:--: | :--:

Add search session index

---

build.gradle

- None
- The default number of errors to be shown is not many, so let me increase it then.
-

Increase errors to be shown while compiling jvm stuff

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- close #564 
- Subject says it all.
-
Before | After
:--: | :--:

Applied session tag design in session detail screen

---

frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt
frontend/android/src/main/java/io/github/droidkaigi/confsched2019/DebugApp.kt

- I want to send error to crashlytics  when Timber.e()

Add Crashlytics for Release

---

feature/announcement/src/main/java/io/github/droidkaigi/confsched2019/announcement/ui/AnnouncementFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/SponsorFragment.kt

none
- Fix memory leak associated with groupAdapter
- Avoid holding groupAdapter in Fragment's field
- Make weak reference to groupAdapter in SessionsItemDecoration
none
none

Fix memory leak associated with groupAdapter

---

frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/PageConfiguration.kt
frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml

- close #553
- Add configuration for speaker screen.
- https://github.com/DroidKaigi/conference-app-2019/pull/558
Before | After
:--: | :--:

Delete speaker screen speaker title

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml

- close #149
- I added feature of go to floormap screen from sessiondetail screen.
- https://developer.android.com/topic/libraries/architecture/navigation/

Add feature of go to floormap from sessiondetail

---

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/widget/BottomSheetBehavior.kt

- close #167 
- Use android:layout_height="wrap_content" for RecyclerView
- https://github.com/DroidKaigi/conference-app-2019/issues/167#issuecomment-455617087

Fix layout for BottomSheet

---

model/build.gradle

- close #582 
- Added `features = ["parcelize"]` to model module.

Use only experimental of parcelize

---

model/src/commonMain/kotlin/Filters.kt
model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt

- close #572
- Pick sessions forBeginners when Beginners checked.
- Pick sessions *not* forBeginners when Unspecified checked.
Before | After
:--: | :--:

Fix audience filter

---

frontend/ios/Makefile
frontend/ios/README.md

- No issue
- I had a build error on first build (ref. screenshot), and I resolved it.
- In this PR, I added steps to resolve into **README**, and automated with **Makefile**.
- http://anton0825.hatenablog.com/entry/2014/11/22/000000

Add Makefile for iOS

---

feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/SessionSurveyFragment.kt
feature/survey/src/main/res/drawable/background.xml
feature/survey/src/main/res/layout/fragment_session_survey.xml
feature/survey/src/main/res/layout/item_session_survey.xml
frontend/android/src/main/AndroidManifest.xml

- #65 
- Add top of screen design
- fix input mode
-
Before | After
:--: | :--:

Fix SessionSurvey layout design

---

frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionDataSource.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionHeaderView.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewController.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewModel.swift
frontend/ios/DroidKaigi 2019/data/SessionByStartTime.swift

- close #592
- Show session start time on header for iOS App
- 
Before | After
:--: | :--:

Show session start time on header for iOS App

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpacerItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpeechSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableDividerDecoration.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableItemDecoration.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableLayoutManager.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableRoomLabelDecoration.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableTimeLabelDecoration.kt
feature/session/src/main/res/layout/fragment_tabular_form_session_page.xml
feature/session/src/main/res/layout/item_tabular_service_session.xml
feature/session/src/main/res/layout/item_tabular_spacer.xml
feature/session/src/main/res/layout/item_tabular_speech_session.xml
feature/session/src/main/res/values/dimens.xml
model/src/commonMain/kotlin/Room.kt

- reference #150 
- Draft TimeTableLayoutManager
- Implement View Recycling on scrolling (LayoutManager)
- save first visible item position or scroll position and restore it (LayoutManager)
- implement scrollToPosition (LayoutManager)
- fix timezone
- ui improvement
- use SafeArgs

Draft TimeTableLayoutManager

---

frontend/ios/README.md

- I have got stuck for hours 😢

Add iOS trouble shooting

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
feature/session/src/main/res/layout/fragment_tabular_form_session_pages.xml

- close #622
TabLayout without using ViewPager in TabularFormSessionPagesFragment

Stop using ViewPager for TabularFormSessionPagesFragment

---

scripts/parse_dg_response

- None
- Although the url of the distribution was unchanged, bot posted the same comment. 😞 
-

Allow bot to post DeployGate Distribution only once

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
feature/session/src/main/res/layout/item_session.xml
feature/session/src/main/res/values/dimens.xml
frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml

- You can go to the session survey from the session list.

Enable session list to session survey

---

frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift

- none
- add ripple effect to Session list(TableViewCell) 
- using MaterialComponents for iOS
- https://github.com/material-components/material-components-ios/tree/develop/components/Ink
Before | After
:--: | :--:

[ios]add ripple effect to tableViewCell

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- We should show ripple effect when touch survey button
- Currently, we can use session survey for service session. So we should remove it when service session.

Fix session detail survey button ripple and hide when service session

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpeechSessionItem.kt
frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml

- close #619
- TabularSpeechSessionItem selected open session detail
- TabularServiceSessionItem selected open session detail
- https://developer.android.com/topic/libraries/architecture/navigation/navigation-implementing
Before | After
:--: | :--:

Open session detail when session click in session time table

---

frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
frontend/ios/DroidKaigi 2019/Scenes/MainViewController.storyboard
frontend/ios/DroidKaigi 2019/Scenes/MainViewController.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewController.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewModel.swift
frontend/ios/DroidKaigi 2019/Scenes/StartViewController.swift
frontend/ios/DroidKaigi 2019/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
frontend/ios/DroidKaigi 2019/Settings.bundle/com.mono0926.LicensePlist.plist
frontend/ios/DroidKaigi 2019/Settings.bundle/com.mono0926.LicensePlist/XLPagerTabStrip.plist
frontend/ios/DroidKaigi 2019/data/Day.swift
frontend/ios/Podfile
frontend/ios/Podfile.lock

I'm not very familiar with MVVM, therefore I might destroy your architecture. If so, please reject this PR 🙏 
-  PagerTabStrip for iOS
- https://github.com/xmartlabs/XLPagerTabStrip
Before | After
:--: | :--:

[Proposal] PagerTabStrip for iOS

---

.circleci/config.yml

- Degrade since #650 
- Need to store a universal apk as well
-

Store the generated universal apk as well

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionPagesActionCreator.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/action/Action.kt

- close #446
- Add OnTabSelectedListener#onTabReselected to SessionPagesFragment.
-
For test, replaced `DateTime.nowUnixLong()` with `DateTime.createAdjusted(year = 2019, month = 2, day = 7, hour = 8, minute = 30).unixMillisLong`

Scroll to current session

---

frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewController.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewModel.swift

- close #660
- Change fetch sessions timing

Fix #660 for iOS

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt

- close https://github.com/DroidKaigi/conference-app-2019/issues/661
- When day2, open day2 time table 
-
Before | After
:--: | :--:

open day2 time table

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableDividerDecoration.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableLayoutManager.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableRoomLabelDecoration.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableTimeLabelDecoration.kt

- close #150
- close #614
- Implement View Recycling on scrolling for TimeTableLayoutManager 
- Loop TimeTable horizontally (optional)
Before | After
:--: | :--:

Implement View Recycling on scrolling for TimeTableLayoutManager 

---

frontend/android/src/main/res/menu/menu_nav_drawer.xml

- We don't have setting item, so I removed setting navigation item.
- If we can add a setting item, we will uncomment it.

Remove setting while waiting  for adding setting item

---

frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/util/SessionAlarm.kt

- close #685
Before | After
:--: | :--:

notificationの表示不具合を修正

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionPagesActionCreator.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/action/Action.kt

- close #684
- When sessions are loaded, if it is first time for the Fragment, scroll to current session.
- It will never scroll automatically at opened unless you kill the MainActivity
- none
The time of the device was set 2019/02/08 15:00

Open current session when first loading

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt

- close #683
- Apply favorite immediately and little refactor

Apply favorite immediately

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/drawable/ic_date_range_black_24dp.xml
feature/session/src/main/res/menu/menu_session_detail_bottomappbar.xml
feature/session/src/main/res/values/strings.xml
feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ActivityActionCreator.kt

- no issue.
How about a new feature?
This PR proposes a feature to insert a calendar events on the session detail screen.
Add Calendar Button (SessionDetail)  | Insert new events (Google Calendar) | Saved (Google Calendar)
:--: | :--: | :--:

[Proposal] new feature to insert a calendar events

---

.travis/android/update_github_release.bash

- Related to #706 
- jq returned null so Bash paniced 🤷‍♂️

Fixed a failure of a travis script iff no github release exists

---

README.md

Add Android Studio Preview version link for README

---

data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/RoomDatabase.kt
data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/dao/AnnouncementDao.kt
data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/dao/SessionSpeakerJoinDao.kt
frontend/android/build.gradle

- close #724 
- we should not database.clearAllTables() for session survey

Fix db clear when relaunch

---

buildSrc/src/main/java/dependencies/Versions.kt

- 1.0.0 is test version for release
- This version is the first release version of Android App

Update version to 1.0.1

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpeechSessionItem.kt

- close #712 
- AssistedInject for TabularServiceSessionItem,TabularSpeechSessionItem
-
Before | After
:--: | :--:

AssistedInject for SessionItem

---

feature/sponsor/src/test/java/io/github/droidkaigi/confsched2019/SponsorDummyDatas.kt
feature/sponsor/src/test/java/io/github/droidkaigi/confsched2019/sponsor/ui/store/SponsorStoreTest.kt

- close #723
- Add test for `SponsorStore`
- Refer to `AnnouncementStoreTest`
- 
Before | After
:--: | :--:

Add test for SponsorStore

---

.travis/android/update_github_release.bash

- None
- This PR affects only to Travis

Fixed a bug when getting a release id

---

feature/staff/build.gradle
feature/staff/src/test/java/io/github/droidkaigi/confsched2019/StaffDumyDatas.kt
feature/staff/src/test/java/io/github/droidkaigi/confsched2019/staff/ui/store/StaffSearchStoreTest.kt

- close #721
- Add test for `StaffSearchStore`
- Refer to `AnnouncementStoreTest`
-
Before | After
:--: | :--:

add test for StaffSearchStore

---

feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt

Add english privacy policy

---

frontend/android/build.gradle
frontend/android/proguard-rules-production.pro
frontend/android/src/staging/AndroidManifest.xml
frontend/android/src/staging/java/io/github/droidkaigi/confsched2019/StagingApp.kt

- None
- The title says everything

Creatae StagingApp class for staging build type

---

frontend/ios/DroidKaigi 2019/Info.plist

- Update iOS App version to 1.1

Update iOS App version to 1.1

---

frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionDataSource.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableHeaderView.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewController.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewModel.swift

- None
- Just as the title
Before | After
:--: | :--:

[iOS] Add a table header for showing the session start day

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
feature/session/src/main/res/layout/fragment_tabular_form_session_pages.xml

- close #741 
- The place to create TabularFormSessionPageFragment is only onCreate()
- Reuse TabularFormSessionPageFragment of displayed before goto session detail.
- None
Before | After
:--: | :--:

Fix when back to tabular session, the scroll progress is reset

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStore.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt

- We call SessionPagesActionCreator.load() in SessionPagesFragment. So TabularFormSessionPageFragment favorite is not applied.
1. go to TabularFormSession
2. go to session detail
3. favorite
4. back (not applied!!!)

Fix TabularFormSessionPageFragment favorite is not applied

---

frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt

- close #775 
- NavigationDrawerで遷移できる画面はハンバーガーアイコンに修正
Before | After
:--: | :--:

NavigationDrawerで遷移できる画面はハンバーガーアイコンに修正

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimetableLayoutManager.kt

- close #617
- close #792
- implement TimetableLayoutManager#scrollToPosition.
- fix a bug for view recycling.
- remove TimetableLayoutManager#shouldLoopHorizontally
none
none

Implement TimetableLayoutManager#scrollToPosition

---

feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
feature/session/src/main/res/values/strings.xml
frontend/ios/DroidKaigi 2019/Scenes/Detail/SessionDetailHeaderTableViewCell.swift
frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
model/src/commonMain/kotlin/Session.kt
model/src/commonMain/kotlin/SessionType.kt

Delete lunch room

---

feature/session/src/main/res/layout/item_session.xml

- close #799 
- Just add gravity and fixed!
-
Before | After
:--: | :--:

Fix icon and message align

---

buildSrc/src/main/java/dependencies/Versions.kt

Update version to 1.0.3

---

README.md

Update images in README

---

feature/contributor/build.gradle
feature/contributor/src/main/java/io/github/droidkaigi/confsched2019/contributor/ContributorFragment.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2019/contributor/actioncreator/ContributorActionCreator.kt
feature/contributor/src/test/java/io/github/droidkaigi/confsched2019/ContributorDummyData.kt
feature/contributor/src/test/java/io/github/droidkaigi/confsched2019/contributor/actioncreator/ContributorActionCreatorTest.kt
feature/contributor/src/test/java/io/github/droidkaigi/confsched2019/contributor/store/ContributorStoreTest.kt
feature/contributor/src/test/java/io/github/droidkaigi/confsched2019/contributor/ui/actioncreator/ContributorActionCreatorTest.kt

- close #717 
- close #722 
- Add Contributor ActionCreator test
- Rename package from action to actioncreator
- Fix typo on comment
- Add Contributor Store test

Add Contributor ActionCreator and Store test

---

scripts/parse_dg_response

- None
- I will be talking about CI stuff though, the CI has been failing since yesterday night due to me. lol.

Don't run the script unless pull request

---

scripts/ci.env.source
scripts/parse_dg_response

- #828 
- 🤔 ... stable CI has gone

Fixed pull request number handling on linux

---

scripts/parse_dg_response

- none
- Remained buffering caused a failure 🤷‍♂️ 
-

Finally, fixed the master CI

---

.circleci/config.yml

Initialize bash env even on go vm

---

build.gradle
buildSrc/src/main/java/dependencies/Dep.kt

Update Android Gradle Plugin and Coroutines
