- feature/session/src/main/res/layout/fragment_session_detail.xml
- close #175
- By setting to `android:textIsSelectable="true"`, text of session description can be selected.
- https://developer.android.com/reference/android/widget/TextView#attr_android:textIsSelectable
Before | After
:--: | :--:
> To selectable the session description

- frontend/android/src/main/res/layout/activity_main.xml
- close https://github.com/DroidKaigi/conference-app-2019/issues/196
- toolbar changes the height from 64dp to wrap_content
- https://developer.android.com/training/multiscreen/screensizes?hl=ja#TaskUseWrapMatchPar
Before | After
:--: | :--:
> Fix hamburger icon and title misaligned

- feature/session/src/main/res/layout/fragment_session_detail.xml
- close #190
- Changed `android:backgroundTint` to `app:backgroundTint`
- https://developer.android.com/reference/android/R.attr#backgroundTint
- https://issuetracker.google.com/issues/37126253
Before | After
:--: | :--:
> Fixed the bugs to backgroundTint of FloatingActionButton on Android 5.0

- feature/about/src/main/res/values/strings.xml
- close #142
- Add strings.xml resources in English for About screen
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/res/values/strings.xml
> Add English recources for About screen

- feature/session/src/main/res/layout/layout_title_chip.xml
- close #172 
- set chipSurfaceColor ="[at]android:color/transparent"
Default chipSurfaceColor is `#FFFFFF`. (if light theme)
[ChipDrawable](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/chip/ChipDrawable.java) has surface layer and background. Probably the cause is this.
https://github.com/material-components/material-components-android/blob/6c70169e8d4ae77429a9c57785e443b2a18b4aa3/lib/java/com/google/android/material/chip/ChipDrawable.java#L593-L594
Before | After
:--: | :--:
> Delete thin line in the tab

- ext/android-extension/src/main/java/io/github/droidkaigi/confsched2019/ext/android/CoroutinePlugin.kt
related to: Rethink how to inject Coroutine Dispacthers #236
Simplify handler code of CoroutinePlugin.
use invoke() instead of let().
none
none
> Simplify handler code of CoroutinePlugin.

- .gitignore
- .idea/dictionaries/dic.xml
- none
- Please try reopen Android Studio project. The warnings of some unique character string treated as typo has disappeared.
- https://note.mu/nikkei_staff/n/n5685d32e6540
>11.3 Typo Lint を辞書運⽤で制御する
Before | After
:--: | :--:
> Add some unique character string treated as typo to the dictionary

- data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/response/SessionResponseImpl.kt
- data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/response/SessionResponse.kt
- data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/CacheDatabase.kt
- data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/entity/SessionEntityImpl.kt
- data/db-room/src/main/java/io/github/droidkaigi/confsched2019/data/db/entity/mapper/SessionDataMapperExt.kt
- data/db/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/db/entity/SessionEntity.kt
- data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/mapper/SessionMappers.kt
- feature/session/src/main/res/layout/fragment_session_detail.xml
- feature/session/src/main/res/layout/item_session.xml
- feature/session/src/main/res/values-ja/strings.xml
- feature/session/src/main/res/values/strings.xml
- feature/session/src/test/java/io/github/droidkaigi/confsched2019/SessionDummyDatas.kt
- model/src/commonMain/kotlin/Session.kt
- close #152
- show simultaneous interpretation tag on session view when `interpretationTarget` is true.
> show simultaneous interpretation tag on session view

- data/api-impl/build.gradle
- model/build.gradle
- model/src/commonMain/kotlin/LocaleMessage.kt
- model/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/model/Lang.kt
- model/src/jvmMain/kotlin/LocaleMessage.kt
- A part of #136
- Now `:model` module can build for iOS Framework! 🎉
- `./gradlew :model:build` and you can see `model.framework` in `model/build/bin/ios/main/(debug|release)/framework`
- To use "SDK_NAME" environment variable to detect architecture of preset.
- http://matsukaz.hatenablog.com/entry/2015/07/06/090933
- https://qiita.com/nomadmonad/items/c3b6d04627df4d966f8e#nslocale%E3%81%AE%E4%BD%95%E3%81%AB%E8%A8%AD%E5%AE%9A%E3%81%95%E3%82%8C%E3%82%8B%E3%81%AE%E3%81%8B
> Make :model buildable for iOS Framework

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt
- feature/session/src/main/res/layout/fragment_session_page.xml
- feature/session/src/main/res/layout/layout_chip.xml
- feature/session/src/main/res/values/styles.xml
- frontendcomponent/androidcomponent/build.gradle
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/widget/EventFilterView.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/widget/FilterChip.kt
- frontendcomponent/androidcomponent/src/main/res/drawable/tag_clear.xml
- frontendcomponent/androidcomponent/src/main/res/values-ja/strings.xml
- frontendcomponent/androidcomponent/src/main/res/values/attrs.xml
- frontendcomponent/androidcomponent/src/main/res/values/strings.xml
- frontendcomponent/androidcomponent/src/main/res/values/styles.xml
- frontendcomponent/androidcomponent/src/main/res/values/themes.xml
- #52
- #52 is not completed only with this PR
- Remaining work: Apply coloring to the chips after design spec is updated. See https://github.com/DroidKaigi/conference-app-2019/issues/52#issuecomment-452365784
- Implemented chip animation of filter chips
- The animatable chips are implemented by custom view `FilterChip`
- `FilterChip` is copied from iosched's [`EventFilterView`](https://github.com/google/iosched/blob/d8bc48b20c132b519879eda3a8e9af120519e159/mobile/src/main/java/com/google/samples/apps/iosched/ui/schedule/filters/EventFilterView.kt)
- I've modified following points of `EventFilterView` for this app
- Changed class name to `FilterChip`
- This view can be used for chips of any types of filter. It might be better to remove "event" from class name
- I don't have strong …
> Introduce filter chip animation brought from iosched 2018

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt
- feature/session/src/main/res/layout/fragment_session_detail.xml
- feature/session/src/main/res/values/strings.xml
- close #153 
- Added SessionBottomAppBarBehavior class
- If screen be able not to scrolled, it makes to slide the bottom app bar
-
Before | After
:--: | :--:
> Fix to hide BottomAppBar when session detail can not scroll

- .circleci/config.yml
- .circleci/scripts/retry_command
- build.gradle
- scripts/danger/Dangerfile.assertions
- #305 
- I know people love faster builds.
- `dependencies` does not download all dependencies, and also nothing will be downloaded as for this project.
- `androidDependencies` does not contain kapt and custom configurations
- So we need a task to download kapt and custom configurations. After that, let's combine it with `androidDependencies`.
- A html reporter was downloaded every time but it was not used on CI
-
> Enable offline build on the CI

- feature/announcement/build.gradle
- feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/AnnouncementDummyDatas.kt
- feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/actioncreator/AnnouncementActionCreatorTest.kt
- feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/action/Action.kt
- close #294 
- Add unit test for AnnouncementActionCreator/AnnouncementStore
- Change the action of Announcement to data class
-
Before | After
:--: | :--:
> Add unit test for AnnouncementActionCreator/AnnouncementStore

- buildSrc/src/main/java/dependencies/Dep.kt
- feature/system/build.gradle
- feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ActivityActionCreator.kt
- close #289
- change to use Chrome Custom Tab
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ActivityActionCreator.kt#L10
What do you feel about the toolbar color?
I chose primaryColor(#F63529 ) but I feel kind of strong.
Before | After
:--: | :--:
> Use Chrome Custom Tab for open url

- feature/session/src/main/res/layout/fragment_session_page.xml
- close #315 
- Add 8dp space on both sides of the session tab.
-
Before | After
:--: | :--:
> Add space on both sides of the session tab.

- frontend/android/build.gradle
- None
- Delete language resources that are not Japanese and English by resConfigs
- Support libraries includes string resources other than Japanese and English
- Effect : Reduce apk size
- https://developer.android.com/studio/build/shrink-code?#unused-alt-resources
- https://qiita.com/tatsuhama/items/814471b79c5d572f77e9
- https://github.com/DroidKaigi/conference-app-2018/pull/129
Before | After
:--: | :--:
> Delete language resources that are not Japanese and English by resConfigs

- buildSrc/src/main/java/dependencies/Dep.kt
- frontend/android/build.gradle
- none
- Fixed warning at clean build. Changed to specify version
```
Conflict with dependency 'org.jetbrains.kotlinx:kotlinx-coroutines-android' in project ':frontend:android'. Resolved versions for runtime classpath (1.0.1) and compile classpath (1.0.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to /Users/wataru/Develop/conference-app-2019/frontend/android/build.gradle:	
Conflict with dependency 'com.squareup.okio:okio' in project ':frontend:android'. Resolved versions for runtime classpath (1.14.0) and compile classpath (1.13.0) differ. This can lead to runtime crashes. To resolve this issue …
```
> fix version conflict at clean build

- buildSrc/src/main/java/dependencies/Dep.kt
- data/api-impl/build.gradle
- data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
- data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiComponent.kt
- data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
- data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
- data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/ApiModule.kt
- data/api/build.gradle
- data/db-room/build.gradle
- data/db/build.gradle
- data/firestore/build.gradle
- data/repository-impl/build.gradle
- data/repository/build.gradle
- ext/log/build.gradle
- A part of #136
- Now some modules below can build for iOS Frameworks! 📱 
- `:data:api`
- `:data:api-impl`
- `:data:repository`
- `:data:firestore`
- `:data:db`
- `:ext:log`
- How can we implement alternative of `:data:db-room` and `:data:firestore-impl` ...? 🙄 
- https://qiita.com/nosix/items/50166b1664e6946aafe9
> Make some modules buildable for iOS Framework.

- model/src/commonMain/kotlin/Session.kt
- None.
- switch views between a 24-hour clock at session detail page.
- None.
Before | After
:--: | :--:
- session list page is 24-hour clock, there  is no problem.
> Fix time format to 24-hour clock

- build.gradle
- frontend/android/build.gradle
- frontendcomponent/androidcomponent/build.gradle
- frontendcomponent/androidtestcomponent/build.gradle
- close #168
- use Maven Central mirror following to https://storage-download.googleapis.com/maven-central/index.html
- https://storage-download.googleapis.com/maven-central/index.html
There is no screenshot but build speed faster than before, I could not measure accurately though.
The following is synchronization time on my MacBook Air. I only measured once.
Before | After
:--: | :--:
synced successfully 10m 29s 199ms | synced successfully 8m 30s 38ms
> use Maven Central mirror hosted on Google Cloud Storage for faster build

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
- close #324
- Time texts on session list are drawn by `SessionsItemDecoration`
- `SessionsItemDecoration` processes `RecyclerView`'s children ordered by index
```kotlin
var lastTime: String? = null
for (i in 0 until parent.childCount) {
val view = parent.getChildAt(i)
val position = parent.getChildAdapterPosition(view)
if (position == -1 || position >= groupAdapter.itemCount) return
val time = getSessionTime(position) ?: continue
if (lastTime == time) continue
lastTime = time
```
- It skips drawing text if the session time of **previous view** is same
- However, view index order and item position order can be different in RecyclerView
- i.e. Drawing text should be skipped if the session time of **previous item** (not of previous view) is same
- Although they are luckily matched in most …
> Fix SessionsItemDecoration not to draw unexpected time text

- frontendcomponent/androidcomponent/build.gradle
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/dispatcher/Dispatcher.kt
- frontendcomponent/androidcomponent/src/test/java/io/github/droidkaigi/confsched2019/dispatcher/DispatcherTest.kt
- close #157
- `Action.UserRegistered` dispatched from `UserActionCreator` was randomly lost in race condition
- If `Action.UserRegistered` is lost, `UserStore.registered` doesn't become `true` and `SessionContentsActionCreator.refresh()` never be triggered from `SessionPagesFragment`
- It make session pages keep empty
- The loss is caused because of the implementation of `Dispatcher.launchAndDispatch()`:
```kotlin
class Dispatcher @Inject constructor() {
private val _actions = BroadcastChannel<Action>(Channel.CONFLATED)
// ...
fun launchAndDispatch(action: Action) {
GlobalScope.launch {
_actions.send(action)
}
}
```
- The actual class of `_actions` is [`ConflatedBroadcastChannel`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-conflated-br …
> Fix session list loading error caused because Dispatcher loses action

- feature/sponsor/src/main/res/layout/item_header.xml
- Compiler warns that binding variable `title` collides with view id `title`.
```
w: warning: View field title collides with a variable or import
file:///home/circleci/conference-app-2019/feature/sponsor/src/main/res/layout/item_header.xml Line:18
```
Years ago, it was generating wrong code.
> Fix binding name collision warning

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ImageViewBinding.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ViewBinding.kt
- DataBinding ignores namespace (except for `android`) on `@BindingAdapter`. It have nothing to affect.
```
w: /home/circleci/conference-app-2019/feature/session/build/tmp/kapt3/stubs/debug/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ViewBindingKt.java:9: warning: Application namespace for attribute app:visibleGone will be ignored.
public static final void showHide(@org.jetbrains.annotations.NotNull()
^
w: /home/circleci/conference-app-2019/feature/session/build/tmp/kapt3/stubs/debug/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ImageViewBindingKt.java:9: warning: Application namespace for attribute app:imageUrl will be ignored.
public static final void loadImage(@org.jetbrains.annotations.NotNull()
^
w: …
```
> Remove redundant namespace on BindingAdapter

- buildSrc/src/main/java/dependencies/Dep.kt
- None
- Updated ConstraintLayout. 
I think, if someone may use MotionLayout it may be updated to [2.0.0-alpha03](https://androidstudio.googleblog.com/2018/12/constraintlayout-200-alpha-3.html). 🤔 
- https://androidstudio.googleblog.com/2018/08/constraintlayout-113.html
> Updated ConstraintLayout

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
- feature/session/src/main/res/values/dimens.xml
- close #319
- Change `SessionItemDecoration` to draw lines between time labels.
- No lines will be drawn below the last session.
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpaup_woDHhdXis
Before | After
:--: | :--:
> Draw line between time labels

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
- feature/session/src/main/res/values/dimens.xml
- close #315 
- Add 16dp space between session tab.
- 
Before | After
:--: | :--:
> Add space between session tab.

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
- feature/session/src/main/res/drawable/shape_pill_background.xml
- feature/session/src/main/res/layout/fragment_session_pages.xml
- feature/session/src/main/res/layout/layout_tab_item.xml
- feature/session/src/main/res/values/styles.xml
- close #393 
We can set background of tab item with app:tabBackground.
But it is not set to `background` of TabView.
It's just used to background rendering on onDraw of TabView.
So we cannot set ripple shape with it.
I set CustomView of Tab to do it.
Before | After
:--: | :--:
... | GIF Anim <img src="https://user-images.githubusercontent.com/10704349/51071612-41200100-1697-11e9-939b-b26c0acf8b1f.gif" width="300" />
> Change ripple shape of session tab item

- frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/PageConfiguration.kt
https://github.com/DroidKaigi/conference-app-2019/issues/402
- PageConfiguration members are lowercase too.
- Change it to uppercase.
Before | After
:--: | :--:
> change lowercase of PageConfiguration member name to uppercase.

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SearchActionCreator.kt
- close #406
- Display sessions without entering search queries.
I just fixed this followed by the issue.
But it's was seems show only Speakers on purpose.
Is this change really correct or it was have something special reason?
-
Before | After
:--: | :--:
> Display sessions without entering search queries

- feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ActivityActionCreator.kt
- None.
- Multiple starts of sponsor page by continuous tap.
- Other pages (Twitter, Github) The URL display function is the same.
- None.
Before | After
:--: | :--:
> fixed multiple starts of sponsor page.

- feature/session/src/main/res/layout/fragment_session_page.xml
- close #410
- Fixed that unneeded scrollbar is shown when switching tab.
Just one line 😄 
-
Before | After
:--: | :--:
> Fixed that unneeded scrollbar is shown when switching tab

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
- close #383 
- Delete unneeded listener field at `SpeechSessionItem.onFavoriteClickListener` and `SpeechSessionItem.onClickListener`
https://github.com/h3birth/conference-app-2019/blob/120feccb0acdbbc627ef5a24e01f231a77902cbb/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt#L53-L61
-
Before | After
:--: | :--:
> delete unneeded listener field

- gradle.properties
There's no issues filed for this.
I enabled `org.gradle.parallel` to take advantage of the multi-module setup. The build will run tasks in parallel where possible.
The amount of improved build time depends on the spec of your machine, but it should be faster in general.
Gradle scan reports
Enabled: https://scans.gradle.com/s/y5azqvabdv5yq
Disabled: https://scans.gradle.com/s/rz3r5yqbwt7ji
> Enable org.gradle.parallel for faster build

- build.gradle
- buildSrc/src/main/java/dependencies/Dep.kt
- frontend/android/build.gradle
- frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt
- close [#125](https://github.com/DroidKaigi/conference-app-2019/issues/125)
- Introduce Firebase Crashlytics
- But, Unfortunately, the logs are not clean. I do not know the current cause.
- Maybe, Firebase administrators of DroidKaigi 2019 think that configuration is necessary.
```
I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
I/FirebaseInitProvider: FirebaseApp initialization successful
D/Fabric: Falling back to Crashlytics key lookup from Manifest <-- ???
D/Fabric: Falling back to Crashlytics key lookup from Strings <-- ???
D/Fabric: Falling back to Crashlytics key lookup from …
```
> Introduce Firebase Crashlytics

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
- close #187 
- when user changes device's language some `Chip` s are not updated until reloading/re-binding
This PR changes:
- use `defaultLang()` instead of `systemStore.lang`
- #376 
Before | After
:--: | :--:
> Fix issue #187 use defaultLang instead of systemStore.lang

- frontendcomponent/androidcomponent/src/main/res/values-ja/strings.xml
- `Droidkaigi` -> `DroidKaigi`
Before | After
:--: | :--:
> Fix "Droidkaigi" to camelcase

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
- close #439 
- calculating session time on each onDrawOver that causes unnecessary memory allocation. (it is higher cost needed to calculate DateTime in onDrawOver)
-
Before | After
:--: | :--:
before: increase memory usage about 500MB and more
after: memory usage about 260MB
> Improve SessionsItemDecoration performance

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SpeakerFragment.kt
- close #448 
- I roughly searched with the command: `git grep "AndroidSupportInjection.inject("` and deleted the lines. Please tell me any oversights.
- none
Before | After
:--: | :--:
> Remove injection call from subclass of DaggerFragment

- buildSrc/src/main/java/dependencies/Dep.kt
- close #455
- Because we use old android dispatcher. the app cause crash. So we use new android coroutine dispatcher.
> Update coroutine version with Ktor version

- feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/widget/DottedItemDecoration.kt
- close #188 
- Remove last item divider on About screen
Before | After
:--: | :--:
> Remove last item divider on About screen

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
- close #463 
- After filtering, hide the session header if the session list is empty.  
Before | After
:--: | :--:
> Hide header shadow when list empty

- buildSrc/src/main/java/dependencies/Dep.kt
- close #479
- Bumped Hyperion version 0.9.25
- I didn't reproduce on my essential phone(Android9), so could you check if it is fix?
- none
none
> Bumped Hyperion-Android 0.9.25 ( Fix for SecurityException on API 28)

- data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/mapper/SessionMappers.kt
- feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/AnnouncementDummyDatas.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
- feature/session/src/test/java/io/github/droidkaigi/confsched2019/SessionDummyDatas.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/util/SessionAlarm.kt
- model/src/commonMain/kotlin/Session.kt
- model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/DateTimeTest.kt
- no issue
This PR improve about time zone adjustment.
* Calculate `dayNumber` based on JST.
* Use `toOffset` instead of `plus`.
* Use `toOffsetUnadjusted` to adjust the date components to be JST.
klock's `DateTime` represents a Date in UTC (GMT+00).
When time zone adjusting, we should convert to DateTimeTz.
I also wrote a test code to verify the operation of `DateTime`.
what do you think about this?
-
> Refactor DateTime and Time Zone

- data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiComponent.kt
- data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/UserAgentInterceptor.kt
- None
I think using HTTP with gzip compression is a good way to reduce network traffic.
OkHttp adds `Content-Encoding: gzip` header automatically. However, to enable gzip in GoogleAppEngine, [it must also be included in User-Agent.](https://cloud.google.com/appengine/docs/standard/go/how-requests-are-handled#response_compression)
- https://cloud.google.com/appengine/docs/standard/go/how-requests-are-handled#response_compression
Before ⬇️ 
After ⬇️ 
I confirmed that the traffic of the `timetable` decreased to 1/3 by the Android Profiler.
> Enable gzip compression when api calls

- data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
- data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/DroidKaigiApi.kt
- frontend/ios/DroidKaigi 2019/SessionRepository.swift
- frontend/ios/DroidKaigi 2019/SessionsViewController.swift
- frontend/ios/DroidKaigi 2019/SessionsViewModel.swift
- close #493
- Add ``onError`` callback to ``DroidKaigiApi.getSessions``
- Receive onError in iOS(swift) and implement display alert
Before | After
:--: | :--:
N/A | <img src="https://user-images.githubusercontent.com/401369/51264155-30ee8580-19f9-11e9-8136-007d812c0639.png" width="300" style="max-width:100%;">
I'm not sure that how to raise exception in ``DroidKaigiApi.getSessions``.
I tried turn offline my iPhone but ``getSessions`` returns success(empty response).
So I change [ApiEndpoint](https://github.com/DroidKaigi/conference-app-2019/blob/a5dc5133cf1e1ad4eaad435c4816aa43a2e6cb8d/data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt#L5) to invalid url then I can confirmed call error callback.
> Add error callback for iOS in common module

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
- close #528 
- sort sessions by title
-
Before | After
:--: | :--:
> Sort sessions in search screen

- frontend/ios-combined/build.gradle
- Related #495
- As the comment in the code described, project dependencies shouldn't be added twice. (Kotlin multi-platform plugin did it once. see https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinMultiplatformPlugin.kt#L72 )
- group name depends on the root directory name of the project so ios build failed if we use the directory name except `conference-app-2019`
- https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinMultiplatformPlugin.kt#L72
> Avoid adding project dependencies without using the project name

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreator.kt
- feature/session/src/main/res/values-ja/strings.xml
- feature/session/src/main/res/values/strings.xml
- close #513
- Show original message if toggle session favarite fail
- Network error message is already show on SnackBar when failed favorite. So I just implemented a original message for failed favorite.
-
Before | After
:--: | :--:
> Show original message if toggle session favarite fail

- feature/about/build.gradle
- feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt
- close #554
- Get current commit hash by using `git rev-parse --short HEAD` on build time, and use it on about screen.
Before | After
:--: | :--:
> Add commit hash to about screen

- feature/session/src/main/res/layout/layout_speaker.xml
- close #563
- Added margin at bottom of each speaker.
Before | After
:--: | :--:
> Add margin to speakers list

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
- feature/session/src/main/res/drawable/ic_table_chart_24dp.xml
- feature/session/src/main/res/layout/fragment_tabular_form_session_page.xml
- feature/session/src/main/res/layout/fragment_tabular_form_session_pages.xml
- feature/session/src/main/res/menu/menu_toolbar.xml
- frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt
- frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml
- frontendcomponent/androidcomponent/src/main/res/values-ja/strings.xml
- frontendcomponent/androidcomponent/src/main/res/values/strings.xml
- close #518 
- Add empty Fragments and layouts for tabular form sessions
- I want you to review about names of Fragments and navigation label
- I added newInstance() method on `TabularFormSessionPageFragment` because I think it's gonna get some arguments from safeargs. If it's not necessary, I will delete it.
- I use `SessionPageScope` to inject `TabularFormSessionPageFragment` because I think it has same scope as `SessionPageFragment`.
-
Before | After
:--: | :--:
> Add empty Fragments and layouts for tabular form sessions

- feature/about/src/main/res/layout/item_about.xml
- Added a touch feedback when user taps on items on the About page.
> Add ripple effect to About items

- model/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/model/Lang.kt
`NSLocal.preferredLanguages` returns Language IDs
https://developer.apple.com/documentation/foundation/nslocale/1415614-preferredlanguages
https://qiita.com/m1takahashi/items/e28858198ed8848a2738
> fix ios default local

- feature/floormap/src/main/java/io/github/droidkaigi/confsched2019/floormap/ui/FloorMapFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
- frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml
- model/src/commonMain/kotlin/Room.kt
- close https://github.com/DroidKaigi/conference-app-2019/issues/581
- If the session room name does not contains "Hall", 5F floor map is displayed.
Before | After
:--: | :--:
> Display appropriate map when going from session detail to floormap

- data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
- None
- The server response contains `kind` field so json mode should be non-strict.
-
Before | After
:--: | :--:
> Fixed sponsor page could not be opened due to json strict mode

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt
- close #549 
- Blinking was triggered that checking lineCount after setText (see figure1).
- This PR changes checking lineCount before setText
- and fix SpeakerItem equals method
figure1: slow motion
but at some points, there is a room of improve:
- ellipsis position is not exact same before situation (I think it is difficult to detect exact position before `setText`)
- It seems be better to split to CustomView such a draw logic
-
Before | After
:--: | :--:
> Fix blink SessionDetail is blinking when favorite button clicked

- frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
- frontend/ios/DroidKaigi 2019/Scenes/Session/TagsCollectionViewCell.swift
- cache calculated tableView cell height
To reduce CPU usage, cache `SessioncCalculateHeightTableViewCell` height.
cf.  We create another 'virtual' cell (`SessioncCalculateHeightTableViewCell`)  to calculate `SessionTableViewCell` height every time cell is appearing.
1. Scroll  top to bottom, bottom to top by same speed as possible some times.
2. check `CPU Report (Xcode)`
reduce CPU usage about `5 ~ 10%`.
Before | After
:--: | :--:
> Improve performance by caching UITableViewCell height for iOS

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
- frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml
> SafeArgs導入

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
- frontendcomponent/androidcomponent/src/main/res/values-ja/strings.xml
- frontendcomponent/androidcomponent/src/main/res/values/strings.xml
- close #608 
- in some situation, ellipsis position is shifted
If 5th line (that is prescribed value decided to ellipsize) contains line feed, it is shifted even if using `TextUtils.ellipsize`
so I decided to remove line feed(`\n`) from 5th line and after.
Pros:
- ellipsis positioned at the end of 5th line
Cons:
- in some cases, break 5th line (see 4th before/after screenshot)
how do you think?
Before | After
:--: | :--:
> Fix ellipsis position was shifted in some situation

- frontend/ios/DroidKaigi 2019/Scenes/Session/TagsCollectionViewCell.swift
- frontend/ios/DroidKaigi 2019/Scenes/Session/TagsLeftAlignedCollectionViewFlowLayout.swift
- None
- In small devices (SE, 5s, etc.), long tags is sticking out from a table view
Before | After
:--: | :--:
> Fix max width of tags for iOS

- frontend/android/build.gradle
- close #268 
- Remove **some** warnings by excluding warned kotlin_modules.
```
packagingOptions {
exclude 'META-INF/*.kotlin_module'
exclude 'META-INF/*.version'
exclude 'META-INF/proguard/*.pro'
}
```
We still have other warnings about `/META-INF/services/**` .
Because We need to research what services are required for this app.
Please read [here](https://github.com/DroidKaigi/conference-app-2019/issues/268#issuecomment-457836813) if you'd like to know more.
> Remove some warnings(Not all)

- feature/session/src/main/res/layout/fragment_session_detail.xml
- close #649 
- Fix session detail title's new line with no scrolling.
-
Before | After
:--: | :--:
> Fix session detail title's invalid new line

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
- Should not go to session detail when sessionType.supportDetail is false
- Currently, we can go session detail of lunch
> Should not go to session detail when sessionType.supportDetail is false

- frontend/android/src/main/AndroidManifest.xml
- close #656
- When stateVisible is present, the IME is displayed automatically
- Delete unnecessary options
-
Before | After
:--: | :--:
> Fixed #656 bug

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt
- close #635 
- The SessionPagesFragment is leaked, when it is destroyed before being drawn.
- Change object function to function variable to add at onActivityCreated, remove at onDestroyView.
-
Before | After
:--: | :--:
> Change OnPreDrawListener object to field variable to avoid leak

- build.gradle
- buildSrc/src/main/java/dependencies/Dep.kt
- close #665 
- R8 causes fatal error in Firebase Firestore, 
- https://issuetracker.google.com/issues/114554345#comment17
Before | After
:--: | :--:
> fixed #665 bug

- frontend/ios/DroidKaigi 2019/Scenes/MainViewController.storyboard
- frontend/ios/DroidKaigi 2019/Scenes/Session/SessionsViewController.storyboard
- close #675
- Fix a SafeArea croping issue
- Just specified bottom constraints to superview, not safearea.
-
Before | After
:--: | :--:
> Fix a SafeArea cropping issue

- feature/survey/src/main/res/drawable/circle_background.xml
- feature/survey/src/main/res/layout/item_speaker_icon.xml
- close #647
- Set gray circle to background
-
Before | After
:--: | :--:
> Fixed #647 issue

- data/api-impl/build.gradle
- data/api-impl/src/iosMain/kotlinDebug/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
- data/api-impl/src/iosMain/kotlinRelease/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
- frontend/ioscombined/build.gradle
- close #674 
- In addition to `src/iOSMain/kotlin`, one of
`src/iOSMain/kotlinDebug`
or
`src/iOSMain/kotlinRelease`
is also source directory now, according to Xcode configuration (Debug or Release)
- Move`ApiEndpoint.kt` to `kotlinDebug` and `kotlinRelease` , making it return appropriate endpoint
I couldn't find out the way to tell the configuration value to Kotlin source code. So I decided to switch  the whole source file itself.
`project.findProperty("XCODE_CONFIGURATION")` is used for detecting Xcode configuration. I don't know much about it 😇 but it is already used in `packForXCode` task in ioscombined/build.gradle.
Though I've also changed the api-impl/build.gradle, I think is not used for iOS build 🤔
> [iOS] Change API endpoint according to build configuration

- frontend/ios/Podfile.lock
N/A
- Update LicensePlist to v2.1.0
- https://github.com/mono0926/LicensePlist/releases/tag/2.1.0
Before | After
:--: | :--:
> [iOS] Update LicensePlist to v2.1.0

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
- ref: #664
- アプリ起動時の描画完了前にタップするとクラッシュする問題の対応
- 複数のセッションを同時にタップするとクラッシュする問題の対応
> アプリ起動前タップ&複数セッション同時タップ暫定対応

- frontend/android/build.gradle
- Title says everything
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':frontend:android:processDebugGoogleServices'.
> No matching client found for package name 'io.github.droidkaigi.confsched2019.debug.debug'
```
> Hotfix for No matching client found build error

- README.md
- buildSrc/src/main/java/dependencies/Dep.kt
- AGP 3.4.0 beta 2 and AS 3.4.0 Beta 3 are not compatible.
> Update AGP Version to 3.4.0-beta03

- frontend/ios/DroidKaigi 2019/Scenes/FloorMap/FloorMap.storyboard
- frontend/ios/DroidKaigi 2019/Scenes/MainViewController.storyboard
- no numbering.
Fix a SafeArea cropping issue. 
See attached screenshots.
This PR changes following settings.
**MainViewController.storyboard**
- Fit Button Bar View s trailing/leading edsge to superview.
- Fit Container View's trailing/leading edsge to superview.
**FloorMap.storyboard**
- Fit Button Bar View s trailing/leading edsge to superview.
- Fit Container View's trailing/leading/bottom edsge to superview.
- Fit Scroll View's trailing/leading/bottom edsge to superview.
- Enable Scroll View's Horizontally/Vertically Bounce.
**note**
- Screenshotでは提示できていませんが、スワイプによるページ移動にて次ページの表示内容がSafeArea端から出現するような状況だったため、Container Viewの制約を修正しました。
- FloorMapにてScroll Viewの範囲を画面一杯に広げる修正をしましたが、これの弊害として、デフォルトスケール時にマップの下部がホームインジケータに被る状況となっています。Bounceを有効にすることでユーザが必要に応じてホームインジケータから避けれるようにしました。
-
Before …
> [iOS] Fix safe area cropping issue (Part2).

- frontend/ios/README.md
- settings.gradle
- ref #738
- This PR is just workaround 😭
> Comment out ioscombined module in settings.gradle for fixing Android Studio unresolved reference

- buildSrc/src/main/java/dependencies/Dep.kt
- feature/survey/src/test/java/io/github/droidkaigi/confsched2019/SessionFeedbackDummyDatas.kt
- feature/survey/src/test/java/io/github/droidkaigi/confsched2019/survey/ui/store/SessionSurveyStoreTest.kt
- close https://github.com/DroidKaigi/conference-app-2019/issues/720
- Add session survey store test
- SessionSurveyStore https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/store/SessionSurveyStore.kt#L14
> Add session survey store test

- frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt
- close #755 
- SessionPagesFragment has red background color, others has no background color (= transparent), then it looks flickering on navigating
- before implementation, it also changed background color of SessionPagesFragment
-
Before | After
:--: | :--:
> Fix issue 755: Set background color white except SessionPagesFragment at navigation

- frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableViewCell.swift
- None 🙇 
- match tap action and showing favorite button behavior with android version
Before | After
:--: | :--:
> [iOS] match tap and favorite behavior with android version

- .gitignore
- Following warning is shown when opening the project.
- Because `*.keystore` is listed in `.gitignore`, but `frontend/android/debug.keystore` is tracked.
- Exclude `frontend/android/debug.keystore` from ignored files by `.gitignore`.
> Dismiss warning 'Ignored files found that are tracked'

- model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt
- close #711 
- separates test cases with Session class type (ServiceSession / SpeechSession)
- replaces Parameterized test
- confirmed with the command: `./gradlew :model:jvmTest`
-
Before | After
:--: | :--:
> Refactor FiltersTest

- feature/staff/src/test/java/io/github/droidkaigi/confsched2019/staff/ui/actioncreator/StaffSearchActionCreatorTest.kt
- model/src/commonMain/kotlin/StaffSearchResult.kt
- close #716
- Change modifier of `StaffSearchResult` for testing easily
- Add `StaffSearchActionCreatorTest` for testing `load` and `search` functions
-
> Add StaffSearchActionCreator test

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/TextViewBinding.kt
- close #768
- Quote input `highlightText` with `Pattern.quote()`
- https://docs.oracle.com/javase/jp/8/docs/api/java/util/regex/Pattern.html#quote-java.lang.String-
> Fix crash bug in highlighting text

- buildSrc/src/main/java/dependencies/Dep.kt
- feature/session/build.gradle
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetFavoriteSessionsFragment.kt
- None
- When BottomSheetDaySessionsFragment / BottomSheetFavoriteSessionsFragment is collapsed, pressing the back-key closed the application and it was not intuitive, so I tried to expand it pressing back-key.
- Apply androidx.fragment for using easy onBackKeyPress handling in fragment. But 1.1.0-alpha03 haha :)
- http://androhi.hatenablog.com/entry/2019/01/31/201235
Before | After
:--: | :--:
> Expand BottomSheetFragments(collapsed) when on Back Key Pressed.

- frontend/ios/DroidKaigi 2019/AppDelegate.swift
- remove `UINavigationBar` bottom line
Before | After
:--: | :--:
> Remove NavigationBar Bottom Line for iOS

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/EqualableContentsProvider.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/ServiceSessionItem.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpeechSessionItem.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/item/DividerItem.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/item/EqualableContentsProvider.kt
- frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/item/SearchSectionHeaderItem.kt
- #766 has a small issues. I will fix it 🙇
> [Based on #766] add equalable content provider

- buildSrc/src/main/java/dependencies/Versions.kt
- None
- PlayStore cannot accept the same versionCode once we upload so I've added versionCode offset which is kinda *reserved* version space.
> Add versionCode offset to avoid accidental versionCode duplication 

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt
- close #770
- Cached `existSpeakerView` has been set View.GONE, but missing set View.VISIBLE when it has to be shown.
-
Before | After
:--: | :--:
> Fix missing visiblity change

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SpeakerFragment.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ImageViewBinding.kt
- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt
- feature/session/src/main/res/layout/fragment_speaker.xml
- feature/session/src/main/res/layout/item_speaker.xml
- frontendcomponent/androidcomponent/src/main/res/transition/speaker_shared_enter.xml
- frontendcomponent/androidcomponent/src/main/res/values/strings.xml
- close #185
- SharedElement Transition for Speaker Icon from (Session Detail/Search) Screen to Speaker Screen
- We may consider about NON SharedElement Transition for Speaker Icon
- It looks that non SharedElements appear soon and Speaker Icon moves on them.
- There is no transition when back from Speaker Screen
- I need more investigation
Before | After
:--: | :--:
> feat: SharedElement Transition for SpeakerIcon

- frontend/ios/DroidKaigi 2019/Scenes/Session/SessionHeaderView.swift
- frontend/ios/DroidKaigi 2019/Scenes/Session/SessionTableHeaderView.swift
- no numbering.
Fix a SafeArea layout issue.
See attached screenshots.
-
Before | After
:--: | :--:
> [iOS] Fix safe area layout issue.

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimetableCurrentTimeLineDecoration.kt
- ref #794 
- Avoid IndexOutOfBoundsException when access RecyclerView.getChildAdapterPosition.
-
Before | After
:--: | :--:
> Avoid IndexOutOfBoundsException at RecyclerView.getChildAdapterPosition

- README.md
- none
- Add Google Play badge for published app.
- `conference-app-2019` is already published on Google Play 🎉 
- https://play.google.com/store/apps/details?id=io.github.droidkaigi.confsched2019
Before | After
:--: | :--:
> Add Google Play badge for published app.

- frontend/android/build.gradle
- frontend/android/src/debug/res/values/string.xml
- frontend/android/src/main/AndroidManifest.xml
- frontend/android/src/staging/res/values/string.xml
- no issue
- Current app has same name for debug/staging builds and release build, but their package name is not same. In launcher app screen, we cannot identify which is debug/staging/release build.
-
Build | Before | After
:--: |:--: | :--:
Debug | <img src="https://user-images.githubusercontent.com/10704349/52354698-42650380-2a74-11e9-9317-ca69a95dab5e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/10704349/52354700-42650380-2a74-11e9-8dcb-918396182ce7.png" width="300" />
Staging | <img src="https://user-images.githubusercontent.com/10704349/52354698-42650380-2a74-11e9-9317-ca69a95dab5e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/10704349/52354699-42650380-2a74-11e9-9f96-51fc47194734.png" width="300" />
> Change app name for non-release builds.

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimetableLayoutManager.kt
- none
sometimes View#adapterPosition returns `-1`. So TimetableLayoutManager can not relayout correctly.
use Anchor#top instead of View#adapterPosition
> fix timetable relayout

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/ImageViewBinding.kt
- Cannot open Speaker screen which there is no speaker image
- It is because that Speaker screen wait for loading speaker image for the purpose of SharedElement transition, but there is no speaker image.
https://twitter.com/Pooh3Mobi/status/1093264420090785792
> fix: cannot open speaker screen which no speaker image

- feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt
- close #819 
- The target session is "the first of sessions that are on going" now.
- When some long sessions(for example Code Labs), are on going, this logic is non-intuitive.
- So I changed the logic to below.
- Filter `on going`
- Delete sessions `start time is duplicated`
- Get last session
- Get the session's position in the displayed list
- Scroll
- none
The time of the device was set 2019/02/07 16:05
> Fix current scroll logic
